### ISSUE TITLE
Unable to install python3-zeroconf

### ISSUE THREAD

**Issue by nicolinux** [fieldOfView/OctoPrintPlugin#1]
I am using Mac OS and have switched the global python version with pyenv. But when I try to install the python3-zeroconf module, I get this:

`Could not find a version that satisfies the requirement python3-zeroconf (from versions: )
No matching distribution found for python3-zeroconf`

Since the new Cura brings its own python version, do I have install the module through other means?

**Comment by fieldOfView** [comment]
I don't think so, no. That part of the documentation is from before Cura including zeroconf by itself.
Thanks, I will update the documentation.
