### ISSUE TITLE
How to install on OSX?

### ISSUE THREAD

**Issue by darrelhunt** [fieldOfView/OctoPrintPlugin#15]
I go to:
Applications --> Control+Click on Cura --> Show Package Contents --> Resources --> Plugins

This is where it's confusing
That Plugins folder is empty
But there is a Plugins folder within it that has all the standard Cura Plugins
I put the OctoPrintPlugin in that folder and start Cura
It doesn't find it

I even tried putting it in the empty Plugins folder and nothing
Any ideas?

**Comment by nallath** [comment]
Start Cura, go to help-> show configuration folder. There should be a plugins folder there.

**Comment by fieldOfView** [comment]
What @nallath said.

For completeness, it should also work in the Cura.app/Resources/Plugins folder, or the Cura.app/Resources/Plugins/Plugins folder (nb: the existence of the latter is a bug in the packaging of the application).

If you still cannot get it to work, please put the Cura.log (which you can find in the configuration folder) in a pastebin and post a link here. There may be some log output that is helpful.

**Comment by darrelhunt** [comment]
I've already tried
Cura.app/Resources/Plugins
Cura.app/Resources/Plugins/Plugins

When I go to Help --> Show Configuration Folder, it says here

/Users/darrel/Library/Application Support/cura/plugins
I put it there and it still doesn't show "Connect to Octoprint" under Manage Printers

**Comment by fieldOfView** [comment]
What sort of printer are you using octoprint with?

**Comment by darrelhunt** [comment]
It's a Custom FDM that I've named Prusa Mendel i2

Here's the pastebin

http://pastebin.com/3k9K03he

**Comment by fieldOfView** [comment]
It seems the folder inside plugins is named "OctoPrintPlugin.3". The folder must be named "OctoPrintPlugin".

**Comment by darrelhunt** [comment]
Wierd, looking at it under OSX GUI it looked right
But in a terminal it was in fact named OctoPrintPlugin.3
Renamed it in terminal and it works

Thanks for the help
Might I suggest adding how to find where to put the plugin directory for OSX in the README?

**Comment by fieldOfView** [comment]
Good point
