### ISSUE TITLE
Not printing in Cura 2.4

### ISSUE THREAD

**Issue by alexlinno** [fieldOfView/OctoPrintPlugin#24]
It seems that the Qt for 2.4 calls requestWrite with 5 instead of 4 parameters . i don't know what the 5th parameter is but changing line 257 in OctoPrintOutputDevice.py from
def requestWrite(self, node, file_name = None, filter_by_machine = False):
to
def requestWrite(self, node, file_name = None, filter_by_machine = False, Dummy=False):
it works

**Comment by fieldOfView** [comment]
Please use the 2.4 branch of this plugin when using Cura 2.4. 

I will make the 2.4 branch the default branch when 2.4 is officially released.

**Comment by alexlinno** [comment]
sorry my bad

**Comment by fieldOfView** [comment]
No problem, thanks for trying to fix it.

**Comment by alexlinno** [comment]
Thanks for the nice plug-in btw
