### ISSUE TITLE
sent data

### ISSUE THREAD

**Issue by jon012198** [fieldOfView/OctoPrintPlugin#25]
so it said sending data but none thing happened on the octroprint side  i am useing cura 2.4 on the branch of 2.4

**Comment by fieldOfView** [comment]
In the top-right corner of the cura window, there should be a small overlay over the "print monitor" tab/button. It should be green before you try printing. Is it grey for you?

Did you enter the octoprint api key?

**Comment by jon012198** [comment]
green and key is there it says connected

**Comment by fieldOfView** [comment]
Ok, that's weird. 
Did you select "Store gcode on sd card" or deselect "automatically start print job after uploading"?

**Comment by fieldOfView** [comment]
Perhaps your stderr.log can tell me something. Could you post that to pastebin and post the link here?

**Comment by AlexAhrens** [comment]
Had a similar problem a couple of days ago. A fresh copy solved the problem.

**Comment by fieldOfView** [comment]
A fresh copy of what? Cura, OctoPrintPlugin, or OctoPrint?

**Comment by AlexAhrens** [comment]
Sorry, was in a hurry. A fresh copy of the Plugin downloaded from github. I've deleted the existing one in the Plugin-Folder, started cuts and closed it right away. After that copied the new plugin and gave both the printer and octopi a restart.

**Comment by jon012198** [comment]
[cura.zip](https://github.com/fieldOfView/OctoPrintPlugin/files/801347/cura.zip)

**Comment by jon012198** [comment]
found the problem if you select store on sd card it dose not work  but once it is un selected it works

**Comment by fieldOfView** [comment]
As far as i know, save to SD can take an extremely long time, almost as long as printing the same gcode file; the data must go through the same slow usb serial port. It is not recommended to use that option (perhaps i should remove it)

**Comment by jon012198** [comment]
yah i would get rid of it since on the facebook group i am in people are just using 64gb sd card on the pi so they dont use a sd card on the control board
