### ISSUE TITLE
Cancel Print won't work

### ISSUE THREAD

**Issue by ManuelW77** [fieldOfView/OctoPrintPlugin#31]
Hey there,
if i try to cancel a print, the yes/no question comes but if i hit yes, nothing happens.

**Comment by fieldOfView** [comment]
What versions of Cura, OctoPrint and the OctoPrintPlugin are you using?
I'm pretty sure cancel worked for me last time I tried it.

**Comment by fieldOfView** [comment]
Wait, I see my screwup. Will try to fix it this week.

**Comment by ManuelW77** [comment]
Thanks :)

As hint, it is 2.5 Branch and Cura Beta 2.5

**Comment by fieldOfView** [comment]
This should now be fixed, though I have not yet been able to test the fix. Please test and report. Download the right branch for your Cura installation:
https://github.com/fieldOfView/OctoPrintPlugin/tree/2.5
