### ISSUE TITLE
Stuck "Sending data to OctoPrint" message box

### ISSUE THREAD

**Issue by blole** [fieldOfView/OctoPrintPlugin#34]
Clicking on "Print with OctoPrint" when the printing server is offline opens a "Sending data to OctoPrint" message box that never disappears.

When the server is powered off, there is a loading bar for some seconds first. When it's powered on, but octoprint isn't running, the loading bar disappears quickly, but the message box stays.

![image](https://cloud.githubusercontent.com/assets/651644/25437758/baacbb5a-2a97-11e7-9bfe-3dac5c508011.png)

**Comment by fieldOfView** [comment]
Nice catch. Will create a fix soon(ish).

**Comment by fieldOfView** [comment]
Should be fixed in the 2.6 and master branches
