### ISSUE TITLE
files are not being send to octoprint

### ISSUE THREAD

**Issue by maukcc** [fieldOfView/OctoPrintPlugin#41]
Everything works, except it is not sending the file to the octoprint server

**Comment by fieldOfView** [comment]
What version of Cura, what version of the OctoPrintPlugin?
Do the logs say anything useful?

**Comment by maukcc** [comment]
2.5.99 on ubuntu 16.04 updated yesterday
OctoPrintPlugin 1.3.4

log:
2017-06-15 12:18:10,732 - DEBUG - SliceInfoPlugin.SliceInfo.run [51]: Sending anonymous slice info to [https://stats.youmagine.com/curastats/slice]...
2017-06-15 12:18:10,737 - WARNING - cura.PrinterOutputDevice.address [212]: address is not implemented by this output device.
2017-06-15 12:18:10,738 - WARNING - cura.PrinterOutputDevice.address [212]: address is not implemented by this output device.
2017-06-15 12:18:10,743 - ERROR - OctoPrintPlugin.OctoPrintOutputDevice.startPrint [439]: An exception occurred in network connection: name 'catalog' is not defined
2017-06-15 12:18:11,906 - ERROR - SliceInfoPlugin.SliceInfo.run [58]: An HTTP error occurred while trying to send slice information: HTTP Error 500: Internal Server Error

**Comment by fieldOfView** [comment]
Whoops, I hope I fixed that in time for the final 2.6 build. Thanks for reporting.

**Comment by fieldOfView** [comment]
Fixed here: fc9cd78905af84b60c7c5f0a7cf5c9470253017e

**Comment by averter** [comment]
Sorry to revisit this issue. For some reason I am affected by this same bug. 
I was trying to use the PPA of OctoprintPlugin to update to version 2.6 and get it right, but it seems it's still on 2.4.
Alternatively I have a manual install which is on 2.6 but I don't know how to swap between the version installed by the PPA and the manual one. Can someone help me please?

**Comment by fieldOfView** [comment]
I know nothing about PPAs, so I am going to ping @thopiekar for that.

In the mean time, try using the AppImage. The PPA is not officially supported.

**Comment by thopiekar** [comment]
Using the PPA should make no difference. Like in the AppImage, all Cura* files are readonly.

**Comment by fieldOfView** [comment]
@averter seems to suggest that his 2.6 PPA installation "comes with" the OctoPrintPlugin for Cura 2.4 (ie: the 2.4 branch instead of the 2.6 branch).

**Comment by thopiekar** [comment]
@fieldOfView Shouldn't be the case: https://code.launchpad.net/~thopiekar/+recipe/cura-extra-plugins-stable-daily

**Comment by averter** [comment]
Oh great. I've done some silly mistake while trying to update via PPA  and I ended up scrambling cura. I cannot even start it.

**Comment by averter** [comment]
Nope, it's still on 2.4. How can I get the version that you just shown? Shouldn't an apt-get update do the trick of updating the PPA?

**Comment by thopiekar** [comment]
Well, what I can imagine of is that the upgrade of the plugin is blocked. Take a GUI like Synaptic and check whether the package is really updated or not.

**Comment by averter** [comment]
Thanks :-). I think it is working now. There were two plugins: "Cura-extra-plugin-octoprint" the 2.4 one, and the "Cura-plugin-octoprint" the 2.6 version. I've switched from one to the other and I'm going to test it when at home. I will let you know.

**Comment by thopiekar** [comment]
It is a long time ago, since I renamed the plugin packages, but, however,
glad to hear it worked.

**Comment by maukcc** [comment]
Is there any reason why these extra plugins are not in the Cura ppa? (they are in the appimage)
Then we would not have these uncertainties about what plugin belongs to what version of Cura

**Comment by thopiekar** [comment]
I just renamed the packages. It can sometimes happen that one of these
extra packages can get included into Cura itself - at least in the past it
was more likely.
To avoid any further conflicts I just decided to call all plugin packages
in a common way.

2017-08-15 11:25 GMT+02:00 MaukCC <notifications@github.com>:

**Comment by fieldOfView** [comment]
Note that there's an issuequeue for the PPA packages here:
https://github.com/thopiekar/Cura-packaging/issues
The PPA (and the official AppImage for that matter) are out of my control.

**Comment by averter** [comment]
I strongly suggest to update the README file on the "how to install" section, so that you install "Cura-plugin-octoprint", and not the extra outdated version. It could be misleading.

**Comment by fieldOfView** [comment]
@thopiekar could you make a pull request to correct the installation instructions? Thanks.
