### ISSUE TITLE
webcam is not shown in Cura if the ip address is different to octaprint

### ISSUE THREAD

**Issue by andrasbiro** [fieldOfView/OctoPrintPlugin#43]
As per the title. I'm not 100% sure the issue is with the plugin, but I did see the webcam picture when the webcam server was the same as the octaprint server. Now that the the camera has a different ip, I don't see the webcam.
(my setup has an old raspberry pi, which has the camera and forwards the serial port to TCP port, and octaprint runs on my home server, connecting to both the camera and the TCP server on the raspi)

**Comment by fieldOfView** [comment]
This has been fixed for the version of the plugin that will ship with Cura 2.7

**Comment by fieldOfView** [comment]
OctoPrintPlugin 2.7 gets the webcam-configuration from OctoPrint, including server, port and image orientation. The version for Cura 2.6 just uses a non-configurable default url.

**Comment by andrasbiro** [comment]
Understood, I will wait for 2.7
