### ISSUE TITLE
Send user agent string

### ISSUE THREAD

**Issue by probonopd** [fieldOfView/OctoPrintPlugin#49]
Please send a more informative user agent string than the current `User-Agent: Mozilla/5.0` when calling the APIs.

```
POST /api/files/local HTTP/1.1
(...)
User-Agent: Mozilla/5.0
(...)
```

**Comment by fieldOfView** [comment]
Can you describe why you want/need this?

**Comment by probonopd** [comment]
I am implementing a compatible server speaking the OctoPrint protocol, and to be able to determine which kind of client is resulting in which bugs that would be very useful for me.

**Comment by fieldOfView** [comment]
Any suggestion what the User Agent should be/include?

**Comment by probonopd** [comment]
`User-Agent: OctoPrintPlugin/<VERSION>` maybe?

**Comment by nallath** [comment]
Cura uses Cura-<VERSION>, so OctoPrintPlugin-<VERSION> would be my preference, but only slightly so.

**Comment by fieldOfView** [comment]
Looking at most common user agents, ```Cura/2.7``` would be more in line than ```Cura - 2.7```.
I propose ```Cura/2.7 OctoPrintPlugin/2.7``` for this plugin.

**Comment by fieldOfView** [comment]
Implemented in the master branch, which will roll into the 2.7 branch shortly.
