### ISSUE TITLE
Wrong times displayed?

### ISSUE THREAD

**Issue by probonopd** [fieldOfView/OctoPrintPlugin#51]
I believe something to be wrong here... is the GUI not using `printTime` (in seconds) and `printTimeLeft` (in seconds) from `/api/job`?

![wrong](https://user-images.githubusercontent.com/2480569/29251605-dce401fe-8057-11e7-8080-cf21b4ef9ff2.png)

Full disclosure, the API is not from OctoPrint but from [my own subset](https://github.com/probonopd/WirelessPrinting) of the API, so the issue may well be on my side. Any hints appreciated.

**Comment by fieldOfView** [comment]
Cura defines "Printing Time" as the total (estimated) duration for the print. OctoPrint defines "printTime" as the time spent on the print sofar. See here for how the total (estimated) duration is determined in the plugin:
https://github.com/fieldOfView/OctoPrintPlugin/blob/2.7/OctoPrintOutputDevice.py#L632
