### ISSUE TITLE
Webcam view overlap application buttons

### ISSUE THREAD

**Issue by wociscz** [fieldOfView/OctoPrintPlugin#55]
When i switch to print panel, webcam view shows up, but it is stretched to whole aplication window. It covers top menu and prepare button. 
Menu and buttons are still clickable, but you must fail&try right spot :-)

I have octoprint 1.3.4 (master branch) on raspberry pi 3, with raspberry pi camera module and resolution is set to half of full ccd coverage x 1296 y 972 - 4:3 picture format.

![screenshot from 2017-08-15 15-20-38](https://user-images.githubusercontent.com/19727241/29317674-5b7d6ab6-81cd-11e7-82c1-29e9c4cf81a4.png)

**Comment by fieldOfView** [comment]
This will be fixed with https://github.com/fieldOfView/OctoPrintPlugin/pull/53.
