### ISSUE TITLE
Allow queueing a printjob while OctoPrint is connected but printer is turned off

### ISSUE THREAD

**Issue by overcookedTOFU** [fieldOfView/OctoPrintPlugin#56]
Currently, OctoPrintPlugin issues an error when OctoPrint is online, but the printer is not connected: "OctoPrint is offline. Unable to start a new job."

The plugin should instead send the print job to OctoPrint even when the printer is turned off.

This will allow use of OctoPrint plugins like PSU Control to turn on the printer automatically when a new print job is received and begun.  

Note: OctoPrintPlugin should allow print jobs to be sent even if the setting "start print job automatically after uploading" is enabled.  This goal is to allow the user to begin printing with one click on the "Print with OctoPrint" button.  After receiving the print job, OctoPrint will turn on the printer and begin printing.

**Comment by fieldOfView** [comment]
In Cura 3.1, the dialog that informs the user a job can not be added has a button to queue the job.
