### ISSUE TITLE
Invalid JSON crashes Cura

### ISSUE THREAD

**Issue by probonopd** [fieldOfView/OctoPrintPlugin#59]
Invalid JSON, e.g., in `/api/printer` crashes Cura. It would be nicer if it would show "n/a" values instead (but not crash).

```
{
  "temperature": {
    "tool0": {
      "actual": 60.16 E:0 B:38.7,
      "target": :60.16,
      "offset": 0
    },
    "bed": {
      "actual": 38.7,
      "target": :60.16,
      "offset": 0
    }
  },
  "sd": {
    "ready": 1
  },
  "state": {
    "text": "Operational",
    "flags": {
      "operational": true,
      "paused": false,
      "printing": 1,
      "sdReady": 1,
      "error": false,
      "ready": true,
      "closedOrError": false
    }
  }
}
```

**Comment by fieldOfView** [comment]
Hmm, I am a bit torn here. The plugin is called the OctoPrintPlugin. OctoPrint specifies an API, and follows it. I can't help that you have written a faulty implementation of that same API. Sure, I could put a try/catch around everything, but that is just shoving your problem under my carpet.

If you want to write a PR to fix this, I will consider including it, but I don't think I am going to have time to do this; there is enough on my plate.
