### ISSUE TITLE
Cura 3.2 Beta not working

### ISSUE THREAD

**Issue by SphaeroX** [fieldOfView/OctoPrintPlugin#67]
Thank you very much for the plugin, unfortunately I don't have it under Cura 3.2 see video. I can't send the print to the printer, I can't click the button. So I click on it but nothing happens.

 https://youtu.be/pRVeZM_0g4Q

**Comment by fieldOfView** [comment]
Please try a newer version of the plugin
http://files.fieldofview.com/temp/OctoPrintPlugin.curaplugin
