### ISSUE TITLE
[Cura 3.3] Seems to detect printer, but cannot click "Print with OctoPrint"

### ISSUE THREAD

**Issue by probonopd** [fieldOfView/OctoPrintPlugin#73]
Trying to use my printer with [WirelessPrinting](https://github.com/probonopd/WirelessPrinting) (which implements a subset of OctoPrint API) with Cura 3.3. It seems to find the printer:

![screenshot from 2018-04-10 14-22-48](https://user-images.githubusercontent.com/2480569/38556696-0f55c1b2-3cba-11e8-885c-ca06b58204da.png)

But when I click "Print with OctoPrint" nothing happens at all - no output on the command line either. 

On the Monitor screen it says "Lost connection with the printer".

![screenshot from 2018-04-10 14-26-08](https://user-images.githubusercontent.com/2480569/38556786-671946bc-3cba-11e8-9d46-e8855afbe8d9.png)

Possibly I need to implement more of the OctoPrint API than what was needed before, but how can I debug this? How can I see what the plugin expects and what it is missing?

Reference:
https://github.com/probonopd/WirelessPrinting/issues/30

**Comment by probonopd** [comment]
OK, it seems like what used to be printed to the command line is now hidden away in `$HOME/.local/share/cura/3.3/cura.log`.

```
$ cat ./.local/share/cura/3.3/cura.log
2018-04-10 14:21:23,813 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/home/me/.local/share/cura/3.3/plugins/OctoPrintPlugin/OctoPrintPlugin/OctoPrintOutputDevice.py", line 302, in requestWrite
2018-04-10 14:21:23,815 - ERROR - [MainThread] UM.Logger.logException [85]:     active_build_plate = Application.getInstance().getBuildPlateModel().activeBuildPlate
2018-04-10 14:21:23,817 - ERROR - [MainThread] UM.Logger.logException [85]: AttributeError: 'BuildPlateModel' object has no attribute 'activeBuildPlate'
```

**Comment by fieldOfView** [comment]
There should be an updated version of the plugin in the plugin browser that fixes this issue (see https://github.com/fieldOfView/OctoPrintPlugin/commit/49e30e3e6225bd304f0d7a512c45053856add9a2)

**Comment by fieldOfView** [comment]
In Cura 3.2 and 3.3 no OctoPrintPlugin comes with Cura. You have to install it manually.

The plugin browser should show which version is available (3.3.1 currently), I think you have 3.3.0.

**Comment by probonopd** [comment]
> You have to install it manually.

I have selected it in the plugin browser, yes. Does this download it on demand? That was not clear to me as a user. I thought it came with Cura and just had to be activated. I much preferred the "old way" of it working out-of-the-box...

**Comment by probonopd** [comment]
jfwiw, I don't see an "Update" button...

**Comment by fieldOfView** [comment]
Please open an issue in the Cura tracker, there is little I can do about it (other than fixing their bugs, which I've done enough for a bit).

You can probably "uninstall" (remove?) the plugin and reinstall it.

**Comment by fieldOfView** [comment]
Did uninstalling and installing work?

**Comment by probonopd** [comment]
Define "work" - I have another issue at the moment; namely that the receiving end of this crashes when uploaded through Cura (for reasons that I still need to debug).

**Comment by fieldOfView** [comment]
Ok, but that is not the issue you describe above, and you said it also happens now on 2.7, so I’m blaming your code ;)
