### ISSUE TITLE
Octoprint webcam not visible in Cura 3.3

### ISSUE THREAD

**Issue by Galfinite** [fieldOfView/OctoPrintPlugin#76]
Webcam view is working fine in Cura 3.2.1, but without change to the Octoprint, the webcam does not work in 3.3. I can have both program versions open side by side, and one works, the other doesn't. The printer's active info does update correctly, only the webcam is at issue.

**Comment by edasque** [comment]
I feel that the upload is much slower too, is it just me?

**Comment by fieldOfView** [comment]
@edasque: that would be a separate issue.

**Comment by fieldOfView** [comment]
See also https://github.com/Ultimaker/Cura/issues/3725

**Comment by VMaxx** [comment]
I've used your code to make the Repetier plugin and I the same problem there.  I got it to come up once, but subsequent loads it was gone and I've not gotten it back since.

**Comment by fieldOfView** [comment]
Could you test the fix here?
https://github.com/Ultimaker/Cura/issues/3725#issuecomment-396181967

**Comment by fieldOfView** [comment]
Fix seems to work. A new version of the plugin has been submitted.

**Comment by VMaxx** [comment]
Thanks, this helped me fix the Repetier plugin too.
