### ISSUE TITLE
Stuck at Checking the API key

### ISSUE THREAD

**Issue by muhmuhhum** [fieldOfView/OctoPrintPlugin#78]
Hi, 
when i try to connect to octoprint after i copy&paste the api code inside the textbox i get the message "Checking the API key..." and it wont go away.
Im on Cura 3.3

**Comment by muhmuhhum** [comment]
just my problem

**Comment by fieldOfView** [comment]
You got it working?

**Comment by ericthelin** [comment]
I have been having this same issue on my Mac. I was happy to see this issue
reported. If there is a solution please post it.

**Comment by fieldOfView** [comment]
@ericthelin, if you want me to look in to it, I am going to need your cura.log
