### ISSUE TITLE
Plugin repeatedly needs "Update"

### ISSUE THREAD

**Issue by jameswood** [fieldOfView/OctoPrintPlugin#80]
This plugin is great and has made my workflow super-satisfying.

I am having a problem where the plugin will just stop running. Cura's plugin manager then shows options to Uninstall or Update. Updating fixes the problem (after a Cura restart) for a session, but eventually the plugin will stop again and require another "update" and Cura restart.

<img width="775" alt="screen shot 2018-05-31 at 10 29 59 am" src="https://user-images.githubusercontent.com/1140049/40754687-cdd1154e-64bd-11e8-92a6-5c61f677f0f5.png">

It's not a huge problem, and I think it's probably a Cura problem rather than a plugin problem, but I wondered if anyone had any clues about what I should check?

Thanks for any advice!

**Comment by fieldOfView** [comment]
That is strange, and the first time I hear of this issue.
Could you share the cura.log from your configuration folder? It is probably too large to attach here, so use a service like dropbox or another cloud drive and post a link.

**Comment by jameswood** [comment]
Heyo! Sorry for the delay, as per the standard procedure the problem didn't appear again for some time.

Here are two cura.logs: https://we.tl/bM4zsO4TBq

One was the active log when I first noticed the problem. I've named that one `duringFailure-cura.log`

The other was a fresh log made immediately after the problem reappeared. I have not yet "updated" the plugin. It's called `afterFailure-cura.log`.

Thanks for any help/direction you can give me!

**Comment by fieldOfView** [comment]
Could you upload your cura.cfg file?

**Comment by fieldOfView** [comment]
It looks like you have disabled the plugin in a previous version, and the current version may not let you "undisable" it. Editing the cura.cfg file (once) should help.

**Comment by jameswood** [comment]
I'd rather not upload it because there are passwords, paths, etc in it - but I can see that it includes the line `disabled_plugins = ,OctoPrintPlugin` so I'll delete that and see if it helps. Is there anything else in `cura.cfg` that I should look for?

**Comment by fieldOfView** [comment]
No, just remove that line.

**Comment by jameswood** [comment]
Thank you so much for your help - this fixed it. Sorry for not getting back to you sooner, I thought it was best to make sure the fix stuck, which it did!
