### ISSUE TITLE
Uploads don't upload if printer is offline

### ISSUE THREAD

**Issue by lf-** [fieldOfView/OctoPrintPlugin#84]
Use case: printer is offline for whatever reason but I want to slice the job immediately and print it once the printer is ready. Plugin is configured to *not* "automatically start print job after uploading", so it should be able to just upload it without the printer being online. Actually, this feature could be fleshed out more as well to change the print button text to "Upload to OctoPrint" instead of "Print with OctoPrint".

Edit: There *is* the Queue Job button but that seems like sort of strange user interface given that I have the plugin configured to only upload to OctoPrint rather than print immediately.

**Comment by fieldOfView** [comment]
> it should be able to just upload it without the printer being online

I'll see if I can fix that by skipping the Queue Job button thing when the plugin is configured to not print automatically, for the next release.

> change the print button text to "Upload to OctoPrint" instead of "Print with OctoPrint".

Unfortunately, that is not possible from the plugin; it would require changes in Cura.

**Comment by fieldOfView** [comment]
Main issue should be fixed in the next release
