### ISSUE TITLE
Weird issues with cura beta 3.5

### ISSUE THREAD

**Issue by lenne0815** [fieldOfView/OctoPrintPlugin#86]
Depending on uninstalling / reinstalling the octoprint plugin and restoring my old profiles, cura beta 3.5 "forgets" my printers or crashes right at startup. It also crashes when everything is working "correctly" and i try to connect a printer.

I personally think its an error from my older printer profiles, but couldnt really pin it down.

[cura.log](https://github.com/fieldOfView/OctoPrintPlugin/files/2402685/cura.log)

**Comment by fieldOfView** [comment]
Today a new version of the OctoPrintPlugin was added to Toolbox, which fixes two issues that you were running into. One was my fault, the other too. Could you test if OctoPrintPlugin 3.5.1 works for you?

**Comment by lenne0815** [comment]
Great to hear, ill test it today !

**Comment by lenne0815** [comment]
Tested, works now as expected ! Thank you !
