### ISSUE TITLE
Plugin produces excess HTTP requests

### ISSUE THREAD

**Issue by ArmedSnail** [fieldOfView/OctoPrintPlugin#92]
Cura 3.5.1 on Win10
OctoPrint 1.3.9 with OctoPi 0.15.1 on Raspbery Zero W

I recently had issues with Octoprint not beeing accessible when trying to slice and upload through Cura since the update to 3.5.1.

What I checked so far:
top on Raspberry shows me Octoprint running at ~2% Processor load when Idle and around 98% when Cura is running.
WireShark shows around ten HTTP GET going out when Cura is running so basically the Plugin is spamming my Octoprint until it is not reachable.
Cura Settings everything seems normal but in Printer selection when going into the "Connect to Octoprint" Menu the "checking the API Key" is flashing as if it constantly checks gets an OK and checks again (Cursor is not inside API field).

Also when Octoprint is not running the Plugin will spam "OctoPrint returned an error: Service not Running" or "OctoPrint returned an error: Bad Gateway" for every HTTP GET until Cura crashes
I will open a seperate issue for that if needed.

Wireshark dump of one second with Cura running where .2 is my Computer and .27 the Octoprint server:
[Wireshark.txt](https://github.com/fieldOfView/OctoPrintPlugin/files/2577735/Wireshark.txt)
From %AppData%\cura:
[stderr.log](https://github.com/fieldOfView/OctoPrintPlugin/files/2577781/stderr.log)
[stdout.log](https://github.com/fieldOfView/OctoPrintPlugin/files/2577782/stdout.log)

edit: Attached Wireshark Log since "insert Code" was too long, found some Log Files and uploaded them too

**Comment by fieldOfView** [comment]
Am I correct that your OctoPrint instance is not being automatically listed in the Connect to OctoPrint dialog, and you needed to add it manually?

**Comment by fieldOfView** [comment]
Do you have VMWare installed on the computer that you run Cura on? Or any other "non standard" network adapters? I am looking into why zeroconf.py raises an OSError, and found this:
https://github.com/jstasiak/python-zeroconf/issues/81

**Comment by ArmedSnail** [comment]
> Am I correct that your OctoPrint instance is not being automatically listed in the Connect to OctoPrint dialog, and you needed to add it manually?

It was automatically listed, but it looked as if it was performing a check on the API Key constantly.
I removed it and tried to add it again but now it looks like the Octoprint instance is loosing Focus after 1 or 2 seconds so I am not able to put in an API key.

> Do you have VMWare installed on the computer that you run Cura on? Or any other "non standard" network adapters? I am looking into why zeroconf.py raises an OSError, and found this:
> [jstasiak/python-zeroconf#81](https://github.com/jstasiak/python-zeroconf/issues/81)

I have Oracle Virtual Box installed but without the Networking components.
What looks common is that i have assigned two IP Adresses on my Interface.
When I remove one of them everything works as expected.

So in fact it seems to be a zeroconf issue rather than a Plugin issue.

Thank you for the fast support :)

**Comment by ArmedSnail** [comment]
> Am I correct that your OctoPrint instance is not being automatically listed in the Connect to OctoPrint dialog, and you needed to add it manually?

so after removing the second Adress from my LAN interface I know what you meant by "automatically listed".
It was never listed automatically, maybe because i added it myself some time ago. now it shows up as "octopi._octoprint._tcp.local

**Comment by fieldOfView** [comment]
> So in fact it seems to be a zeroconf issue rather than a Plugin issue.

It actually looks like an issue that affects both zeroconf and the Qt network components. I will see if I can reproduce it by adding a second IP address to one of my interfaces, and once it is reproduced see if it can be worked around. I'mglad you found a workaround though.

**Comment by fieldOfView** [comment]
@ArmedSnail could you test if this version of the plugin behaves better with network interfaces with multiple ipadresses?
http://files.fieldofview.com/cura/OctoPrintPlugin-v5.0.0-2018-11-14T21_29_30Z.curapackage
Just drop the downloaded file into a running Cura window, and restart Cura.

**Comment by ArmedSnail** [comment]
I tested the File provided with multiple IP on CURA 3.5.1 and 3.6.0  and it looks OK.
It seems the detection of Octopi instance is not working anymore because it shows me my "old" configuration and not the one i created for testing purposes.

**Comment by fieldOfView** [comment]
> It seems the detection of Octopi instance is not working

Please elaborate, I don't quite understand. What did you change, what do you expect to happen, what happens instead?

**Comment by ArmedSnail** [comment]
Wehne first running into the Problem that the Plugin was spamming my Octopi, I removed the Octopi instance (called "octopi") from Cura for troubleshooting because I saw it was trying to verify the Key constantly. After that I was able to add it again (with name  "octopi1"), but because it lost Focus it was not possible to enter an API Key.
After removing one of the IP-Adresses from my Interface the problem with spamming and also loosing focus on the configuration was lost. Also it showed a ""octopi._octoprint._tcp.local" that I*ve never seen before. I deleted the "octopi1" and entered my API Key into the "octopi._octoprint._tcp.local" and used it for Printing.

After Importing the File you provided the automatically created "octopi._octoprint._tcp.local" was gone and the "octopi1" shows instead.

hope this helps.

**Comment by fieldOfView** [comment]
Can you post a link to your cura.log?

**Comment by ArmedSnail** [comment]
here is the Log from yesterday
[cura.log](https://github.com/fieldOfView/OctoPrintPlugin/files/2591625/cura.log)

**Comment by fieldOfView** [comment]
Thanks. 

Silly me. Autodiscovery with zeroconf/bonjour still won't work if you have an interface with multiple IP addresses (because I did not change/fix zeroconf.py), but at least it won't crash Cura and your Pi anymore, right?

**Comment by ArmedSnail** [comment]
I can confirm that the spamming stopped and the UI is fulli accessible again :)

**Comment by fieldOfView** [comment]
Wohoo, thanks for confirming
